"""Refactor models to separate payment profiles.

Revision ID: 2f7c72b19544
Revises: b231db1d6ca0
Create Date: 2026-03-31 18:49:04.238545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f7c72b19544'
down_revision = 'b231db1d6ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_payment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    op.create_table('customer_payment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('stripe_account_id'))
        batch_op.drop_column('account_type')
        batch_op.drop_column('stripe_account_id')
        batch_op.drop_column('onboarding_completed')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('stripe_customer_id'))
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index(batch_op.f('stripe_customer_id'), ['stripe_customer_id'], unique=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_account_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('account_type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index(batch_op.f('stripe_account_id'), ['stripe_account_id'], unique=True)

    op.drop_table('customer_payment_profiles')
    op.drop_table('company_payment_profiles')
    # ### end Alembic commands ###
