"""Add customer_payment_methods table.

Revision ID: 61d4eac69401
Revises: 2f7c72b19544
Create Date: 2026-04-01 11:23:56.252463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d4eac69401'
down_revision = '2f7c72b19544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_payment_methods')
    # ### end Alembic commands ###
